feat(patients): Se agrega lógica de manejo de número de expediente
UnsitosDev/UnsiSmile_back pull request #111
Opened 2024-12-27 06:09 UTC by Skar13F

- Implementada la lógica para gestionar el número de expediente en PatientRequest y PatientResponse.
- Actualizados PatientModel, PatientMapper y repository para manejo del número de expediente.
- Añadida la variable de límite para el número de expediente en application.properties.
- Agregado el atributo número de expediente en el script para la migración.

Al crear un paciente, se agrega el número de su expediente 
![image](https://github.com/user-attachments/assets/61750596-497d-428b-863a-5566ca4f4fcb)
al hacer una consulta sobre pacientes, se devuelve también su # de expediente
![image](https://github.com/user-attachments/assets/fd52e1da-5969-44df-a1b9-3a118a61882c)

2024-12-27 22:50 UTC, fr0ste requested changes

2024-12-27 22:50 UTC, fr0ste commented on src/main/java/edu/mx/unsis/unsiSmile/dtos/request/patients/PatientRequest.java
> +    private Long fileNumber;
por qué se pide en un request si es un numero que se maneja directamente en el back ya que es calculado?

2024-12-27 22:50 UTC, fr0ste commented on src/main/java/edu/mx/unsis/unsiSmile/model/patients/PatientModel.java
> +    private Long fileNumber;
considero que una mejor traducción sería: Medical record number

2024-12-27 23:55 UTC, Skar13F commented on src/main/java/edu/mx/unsis/unsiSmile/dtos/request/patients/PatientRequest.java
> +    private Long fileNumber;
este se pide para los que se van a capturar, (los existentes)

2024-12-28 00:21 UTC, Skar13F commented on src/main/java/edu/mx/unsis/unsiSmile/model/patients/PatientModel.java
> +    private Long fileNumber;
la traducción la hice directa, aunque sería buena opción

2024-12-29 18:53 UTC, ElioenaiJs approved these changes

2024-12-29 20:19 UTC, merged