Us 192 change patient id
UnsitosDev/UnsiSmile_back pull request #97
Opened 2024-12-02 21:45 UTC by Skar13F

Relación con pacientes
![image](https://github.com/user-attachments/assets/baade96a-2070-440e-9233-6558984e175b)

Obtener un paciente
![image](https://github.com/user-attachments/assets/7899decc-f547-46b5-82b4-15de9c9147e7)

2024-12-03 18:30 UTC, fr0ste commented
![image](https://github.com/user-attachments/assets/2cee82eb-e339-4150-a87d-235dd184cad4)
se necesita actualizar este end point también

2024-12-03 18:32 UTC, fr0ste commented
![image](https://github.com/user-attachments/assets/47645b08-62a6-4926-9043-6df38737631e)
error relacionado a la petición de cambio anteriormente planteada

2024-12-03 18:32 UTC, fr0ste requested changes
Revisar cambios en donde afecte el UUID

2024-12-11 23:04 UTC, ElioenaiJs approved these changes

2024-12-14 03:57 UTC, fr0ste approved these changes

2024-12-14 03:57 UTC, merged